### PR TITLE
Add more languages

### PR DESCRIPTION
**Pull request by viebel**

### CODE REVIEW

**Comment by brian-dawn** [comment]
This is great, thanks for the improvements! And for giving the community klipse! :D

**Comment by viebel** [comment]
Cool. What is the deployment process for gitbooks plugins?

**Comment by brian-dawn** [comment]
@viebel it's done via npm: https://www.npmjs.com/package/gitbook-plugin-klipse

I did a release so your changes should be up - I can also add you as a collaborator so you can have publish rights on npm all I need is your username there.

**Comment by viebel** [comment]
That would be great.
My username is viebel

**Comment by brian-dawn** [comment]
OK you're added!

**Comment by viebel** [comment]
Cool.
Have you started to write a book with interactive code snippets?

**Comment by brian-dawn** [comment]
A little bit, I'm presently toying around with leveraging gitbook/klipse for a ClojureBridge curriculum. Liking it a lot so far!

**Comment by viebel** [comment]
Oh nice! Something to share?
Let's switch to email...
Viebel@gmail.com

**Pull request merged**
